name: Build and Deploy Python App
trigger:
  - main

parameters:
- name: poolname
  type: string 
  default: 'TestAgentPool'

resources:
- repo: self

variables:
  imageRepo: 'pythonApp'
  tag: 'v1'

stages:        
- stage: Build_And_Push_Image
  jobs:
  - job: Build_Image
    displayName: Build_Image
    pool:
      name: ${{ parameters.poolname }} 
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'svc_acr_cred'
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/code/Dockerfile'
        tags: |
          $(Build.BuildId)
          $(tag)
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: code

- stage: Upload_Artifacts
  dependsOn: Build_And_Push_Image
  jobs:
  - job: UploadArtifacts
    displayName: Upload Artifacts to JFrog
    pool:
      name: ${{ parameters.poolname }}  
    steps:
    - script: |
        # Install JFrog CLI
        curl -fL https://getcli.jfrog.io | sh
        sudo cp jfrog /usr/local//bin
      displayName: 'Install JFrog CLI'

    # - script: |
    #     # Configure JFrog CLI with Artifactory server details
    #     sudo jfrog rt config --url=https://stackroute.jfrog.io/artifactory --user=trialadmin --password=Reset123
    #   displayName: 'Configure JFrog CLI'

    # - script: |
    #     # Publish manifest file to Artifactory
    #     sudo jfrog rt upload /tmp/myagent/_work/1/s/code/*.yml k8s-yaml-generic-local/k8s-manifects/
    #   displayName: 'Publish Manifest File to Artifactory'


