name: Build and Deploy Python App
trigger:
  - main

parameters:
- name: poolname
  type: string 
  default: 'TestAgentPool'

resources:
- repo: self

variables:
  imageRepo: 'pythonApp'
  tag: 'v1'

stages:        
- stage: Build_Image
  jobs:
  - job: Build_Image
    displayName: Build_Image
    pool:
      name: ${{ parameters.poolname }} 
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'svc_acr_cred'
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/code/Dockerfile'
        tags: |
          $(Build.BuildId)
          $(tag)
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: code
